# Generated by Django 4.1 on 2022-08-20 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Location', models.CharField(choices=[('جميع المناطق', 'all'), ('البحر الميت', 'deadSea'), ('جرش', 'jarash'), ('مادبا', 'madaba'), ('عجلون', 'ajlon'), ('الزرقاء', 'zarqa'), ('اربد', 'irbid'), ('البلقاء', 'albalqa'), ('عمان', 'amman'), ('الكرك', 'alkark'), ('العقبة', 'aqaba')], default='all', max_length=150)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('priceOnHoliday', models.IntegerField(blank=True, null=True)),
                ('priceOnNormalDays', models.IntegerField(blank=True, null=True)),
                ('kitchenDetails', models.CharField(blank=True, max_length=250, null=True)),
                ('yardDetails', models.CharField(blank=True, max_length=250, null=True)),
                ('bulidingArea', models.IntegerField(blank=True, null=True)),
                ('poolLenght', models.IntegerField(blank=True, null=True)),
                ('poolWidth', models.IntegerField(blank=True, null=True)),
                ('poolDepth', models.IntegerField(blank=True, null=True)),
                ('bedRoomsNum', models.IntegerField(blank=True, null=True)),
                ('livingRoomNum', models.IntegerField(blank=True, null=True)),
                ('pathRoomNum', models.IntegerField(blank=True, null=True)),
                ('bedsNum', models.IntegerField(blank=True, null=True)),
                ('maxNumOFVistors', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('descrption', models.TextField(blank=True, null=True)),
                ('farmType', models.CharField(choices=[('شبابية', 'mens'), ('عائلية', 'family'), ('مادبا', 'madaba'), ('مناسبات', 'events'), ('الكل', 'all')], default='all', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FarmImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default='defaultImg.jpg', null=True, upload_to='')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmImages', to='base.farmmodel')),
            ],
        ),
    ]
