# Generated by Django 4.1 on 2022-08-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_farmmodel_location_alter_farmmodel_farmtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farmmodel',
            name='bulidingArea',
        ),
        migrations.AddField(
            model_name='farmmodel',
            name='bulidingDetails',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
