# Generated by Django 4.1 on 2022-09-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_bookingmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmmodel',
            name='Location',
            field=models.CharField(choices=[('جميع المناطق', 'all'), ('البحر الميت', 'deadSea'), ('جرش', 'jarash'), ('مادبا', 'madaba'), ('عجلون', 'ajlon'), ('الزرقاء', 'zarqa'), ('اربد', 'irbid'), ('البلقاء', 'albalqa'), ('عمان', 'amman'), ('الكرك', 'alkark'), ('العقبة', 'aqaba'), ('السلط', 'salt')], default='جميع المناطق', max_length=150),
        ),
    ]
